services:

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  docmost:
    build: .
    # image: docmost/docmost:latest
    environment:
      APP_URL: '${APP_URL}'
      APP_SECRET: '${APP_SECRET}'
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: '${REDIS_URL}'
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    networks:
      - web

networks:
  web:
    external: true

volumes:
  docmost:
  caddy_data:
  caddy_config:
